## **Data understanding**

^What i **discovered** :
     5000 jobs , 30 job roles , 17 cities + remote , 109 unique skills. , 53 companies. , No missing values.,
     No duplicates.

 Data understanding is important before we move to the **cleaning section**.

In [1]:
import pandas as pd
df = pd.read_csv("india_job_market_2024_2026.csv")

In [2]:
df.head()

,Job_ID,Job_Title,Company,Company_Type,Industry,City,Location_Tier,Experience_Level,Job_Type,Work_Mode,Salary_LPA,Skills_Required,Education_Required,Openings,Applicants,Company_Rating,Date_Posted
0,IND2025000,Android Developer,Tech Mahindra,MNC,Information Technology,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,30.9,"Kotlin, Java, REST APIs",M.Tech/M.E.,3,276,4.0,2025-10-31
1,IND2025001,QA Engineer,Dream11,Indian Unicorn,Information Technology,Lucknow,Tier 2,Senior (6-10 yrs),Full-Time,Hybrid,58.6,"Selenium, Manual Testing, Postman, API Testing...",B.Tech/B.E.,3,325,4.0,2025-05-19
2,IND2025002,Business Analyst,HAL,PSU/Govt,EdTech,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,18.4,"JIRA, Excel, Power BI",MCA,5,559,3.6,2024-08-21
3,IND2025003,Cybersecurity Analyst,Groww,Startup,Information Technology,Mumbai,Tier 1,Mid (3-6 yrs),Full-Time,Hybrid,21.7,"Penetration Testing, Python, Ethical Hacking, ...",BCA,3,184,3.5,2026-03-18
4,IND2025004,Python Developer,Oracle,MNC,EdTech,Remote,Remote,Junior (1-3 yrs),Full-Time,Remote,8.0,"Docker, REST APIs, AWS, PostgreSQL",MCA,1,64,3.9,2024-10-25

In [3]:
df.shape

(5000, 17)

In [4]:
df.columns

Index(['Job_ID', 'Job_Title', 'Company', 'Company_Type', 'Industry', 'City',
       'Location_Tier', 'Experience_Level', 'Job_Type', 'Work_Mode',
       'Salary_LPA', 'Skills_Required', 'Education_Required', 'Openings',
       'Applicants', 'Company_Rating', 'Date_Posted'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job_ID              5000 non-null   object
 1   Job_Title           5000 non-null   object
 2   Company             5000 non-null   object
 3   Company_Type        5000 non-null   object
 4   Industry            5000 non-null   object
 5   City                5000 non-null   object
 6   Location_Tier       5000 non-null   object
 7   Experience_Level    5000 non-null   object
 8   Job_Type            5000 non-null   object
 9   Work_Mode           5000 non-null   object
 10  Salary_LPA          5000 non-null   float64
 11  Skills_Required     5000 non-null   object
 12  Education_Required  5000 non-null   object
 13  Openings            5000 non-null   int64
 14  Applicants          5000 non-null   int64
 15  Company_Rating      5000 non-null   float64
 16  Date_Posted         5000 non-null   object
dtypes: float64(2), int64(2), object(13)
memory usage: 664.2+ KB

In [6]:
df.isnull().sum()

Job_ID                0
Job_Title             0
Company               0
Company_Type          0
Industry              0
City                  0
Location_Tier         0
Experience_Level      0
Job_Type              0
Work_Mode             0
Salary_LPA            0
Skills_Required       0
Education_Required    0
Openings              0
Applicants            0
Company_Rating        0
Date_Posted           0
dtype: int64

In [7]:
df.nunique()

Job_ID                5000
Job_Title               30
Company                 53
Company_Type             4
Industry                15
City                    17
Location_Tier            3
Experience_Level         5
Job_Type                 4
Work_Mode                3
Salary_LPA             728
Skills_Required       4817
Education_Required       8
Openings                 7
Applicants             989
Company_Rating          19
Date_Posted            697
dtype: int64

In [8]:
df['Job_Title'].value_counts()

Job_Title
Software Engineer            336
Backend Developer            278
Full Stack Developer         260
Data Analyst                 254
Java Developer               249
Python Developer             246
React Developer              224
Data Scientist               218
Business Analyst             198
Frontend Developer           193
DevOps Engineer              192
Data Engineer                183
Android Developer            172
Node.js Developer            169
Machine Learning Engineer    169
Product Manager              163
AI Engineer                  156
Cloud Engineer               143
QA Engineer                  138
Technical Lead               137
UI/UX Designer               125
Power BI Developer           113
MLOps Engineer               110
iOS Developer                104
Cybersecurity Analyst         96
Engineering Manager           85
NLP Engineer                  81
Research Scientist            80
Computer Vision Engineer      76
Blockchain Developer          52
Name: count, dtype: int64

In [9]:
df['City'].value_counts()

City
Remote         1992
Mumbai          372
Pune            371
Hyderabad       359
Bangalore       344
Chennai         322
Delhi           318
Indore          103
Bhubaneswar     101
Lucknow          98
Jaipur           98
Kolkata          95
Chandigarh       91
Nagpur           87
Coimbatore       84
Ahmedabad        83
Kochi            82
Name: count, dtype: int64

In [10]:
df['Experience_Level'].value_counts()

Experience_Level
Mid (3-6 yrs)        1378
Junior (1-3 yrs)     1256
Fresher (0-1 yr)     1022
Senior (6-10 yrs)     831
Lead (10+ yrs)        513
Name: count, dtype: int64

In [11]:
df['Work_Mode'].value_counts()

Work_Mode
On-Site    2005
Hybrid     1728
Remote     1267
Name: count, dtype: int64

In [12]:
df['Company_Type'].value_counts()

Company_Type
MNC               1717
Startup           1430
Indian Unicorn    1210
PSU/Govt           643
Name: count, dtype: int64

In [13]:
df.duplicated().sum()

0

In [14]:
df.describe()

        Salary_LPA     Openings   Applicants  Company_Rating
count  5000.000000  5000.000000  5000.000000     5000.000000
mean     19.829440     3.642600   302.072000        3.698420
std      18.136741     4.046942   363.989613        0.424994
min       0.800000     1.000000    14.000000        2.500000
25%       6.800000     1.000000    99.000000        3.400000
50%      13.600000     2.000000   185.000000        3.800000
75%      25.600000     3.000000   321.000000        4.100000
max     115.400000    20.000000  2387.000000        4.300000